releases:
  charts:
    project_id: 3828396
    ref: master
  cng:
    project_id: 4359271
    ref: master
  omnibus:
    project_id: 20699
    ref: master
  gdk:
    project_id: 74823
    branch_name: bump-registry-version-gdk-{VERSION}
    commit_message: Bump Container Registry version to {VERSION}
    ref: main
    mr_title: Bump Container Registry version to {VERSION}
    paths:
      - support/docker-registry
      - lib/gdk/config.rb
      - spec/lib/gdk/config_spec.rb
      - gdk.example.yml
  k8s_gprd:
    project_id: 12547113
    branch_name: bump-registry-version-gprd-{VERSION}
    commit_message: Bump Container Registry version to {VERSION} (gprd)
    ref: master
    mr_title: Bump Container Registry to {VERSION} (gprd)
    paths:
      - bases/gprd.yaml
  k8s_gstg_pre:
    project_id: 12547113
    branch_name: bump-registry-version-pre-gstg-{VERSION}
    commit_message: Bump Container Registry version to {VERSION} (pre/gstg)
    ref: master
    mr_title: Bump Container Registry to {VERSION} (pre/gstg)
    paths:
      - bases/pre.yaml
      - bases/gstg.yaml
  k8s_gprd_cny:
    project_id: 12547113
    branch_name: bump-registry-version-gprd-cny-{VERSION}
    commit_message: Bump Container Registry version to {VERSION} (gprd-cny)
    ref: master
    mr_title: Bump Container Registry to {VERSION} (gprd-cny)
    paths:
      - bases/gprd.yaml


