---
- name: restart networkd
  ansible.builtin.systemd:
    name: systemd-network
    state: restarted

- name: restart valkey
  ansible.builtin.systemd:
    name: valkey-server
    state: restarted

- name: Restart sshd
  ansible.builtin.service:
    name: ssh
    state: restarted
