include:
  - local: .gitlab/ci/validate.yml
  - local: .gitlab/ci/test.yml
  - local: .gitlab/ci/integration.yml
  - local: .gitlab/ci/release.yml

default:
  image: golang:1.17-buster
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - $GOPATH/pkg/mod/
      - bin/

variables:
  BUILDTAGS: "include_gcs,include_oss,continuous_profiler_stackdriver"
  CGO_ENABLED: "1"

stages:
  - validate
  - test
  - integration
  - release

.go-version-matrix:
  parallel:
    matrix:
      - GO_VERSION: [ "1.19" ]

release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  script:
    - apk add --no-cache curl git
    - |
      echo "Generate diff from last release for the latest release"
      git diff --unified=0 HEAD~1 ./CHANGELOG.md | tail -n +6 | sed -e "s/^+//" > ./latestChanges.md
  rules:
    - if: '$CI_COMMIT_TAG'
  release:
    tag_name: $CI_COMMIT_TAG
    name: 'Release $CI_COMMIT_TAG'
    description: './latestChanges.md'