include:
  - local: .gitlab/ci/validate.yml
  - local: .gitlab/ci/test.yml
  - local: .gitlab/ci/integration.yml
  - local: .gitlab/ci/release.yml
  - local: .gitlab/ci/document.yml
  - local: .gitlab/ci/child_jobs.yml
  - component: ${CI_SERVER_FQDN}/gitlab-org/components/danger-review/danger-review@2.0.0
    inputs:
      job_allow_failure: true

default:
  image: golang:$GO_VERSION
  tags:
    - gitlab-org
  cache:
    key:
      prefix: $GO_VERSION
      files:
        - go.mod
        - go.sum
    paths:
      - .GOPATH/pkg/mod/
    policy: pull

variables:
  # default Go version
  GO_VERSION: "1.22"
  BUILDTAGS: "include_gcs,continuous_profiler_stackdriver"
  CGO_ENABLED: "1"
  GOPATH: $CI_PROJECT_DIR/.GOPATH
  GOTESTSUM_VERSION: v1.12.0
  PG_PREV_VERSION: "14"
  PG_CURR_VERSION: "16"
  PG_NEXT_VERSION: "15" # TODO: change to 17 once the stable version is out and the `bitnami/postgresql:17` image is available

stages:
  - validate
  - test
  - integration
  - release
  - child jobs
  - document

.go-pg-version-matrix:
  parallel:
    matrix:
      - PG_VERSION: $PG_PREV_VERSION
        GO_VERSION: [ "1.22", "1.23" ]
      - PG_VERSION: $PG_CURR_VERSION
        GO_VERSION: [ "1.22", "1.23" ]
      - PG_VERSION: $PG_NEXT_VERSION
        GO_VERSION: [ "1.22", "1.23" ]
