include:
  - local: .gitlab/ci/validate.yml
  - local: .gitlab/ci/test.yml
  - local: .gitlab/ci/integration.yml
  - local: .gitlab/ci/release.yml
  - local: .gitlab/ci/release_prepare.yml
  - local: .gitlab/ci/release_tag.yml
  - local: .gitlab/ci/document.yml
  - local: .gitlab/ci/child_jobs.yml
  - local: .gitlab/ci/migrate.yml
  - component: ${CI_SERVER_FQDN}/gitlab-org/components/danger-review/danger-review@2.1.0
    inputs:
      job_allow_failure: true

default:
  retry:
    max: 2
    when:
      - api_failure
      - runner_system_failure
      - scheduler_failure
      - stale_schedule
      - unmet_prerequisites
      - stuck_or_timeout_failure
  image: golang:$GO_VERSION
  tags:
    - gitlab-org
  cache:
    key:
      prefix: $GO_VERSION
      files:
        - go.mod
        - go.sum
    paths:
      - .GOPATH/pkg/mod/
    policy: pull

variables:
  FF_TIMESTAMPS: 1
  # default Go version
  GO_VERSION: "1.23"
  BUILDTAGS: "continuous_profiler_stackdriver"
  CGO_ENABLED: "1"
  GOPATH: $CI_PROJECT_DIR/.GOPATH
  GOTESTSUM_VERSION: v1.12.0
  PG_PREV_VERSION: "15"
  PG_CURR_VERSION: "16"
  PG_NEXT_VERSION: "17"
  GOLANGCI_LINT_VERSION: "2.1.6"

stages:
  - validate
  - test
  - integration
  - migrate
  - release
  - child jobs
  - document

.go-pg-version-matrix:
  parallel:
    matrix:
      - PG_VERSION: $PG_PREV_VERSION
        GO_VERSION: [ "1.23", "1.24" ]
      - PG_VERSION: $PG_CURR_VERSION
        GO_VERSION: [ "1.23", "1.24" ]
      - PG_VERSION: $PG_NEXT_VERSION
        GO_VERSION: [ "1.23", "1.24" ]
