include:
  - local: .gitlab/ci/validate.yml
  - local: .gitlab/ci/test.yml
  - local: .gitlab/ci/integration.yml
  - local: .gitlab/ci/release.yml
  - project: 'gitlab-org/quality/pipeline-common'
    file:
      - '/ci/danger-review.yml'

default:
  image: golang:$GO_VERSION-buster
  tags:
    - gitlab-org
  cache:
    key:
      prefix: $GO_VERSION
      files:
        - go.mod
        - go.sum
    paths:
      - .GOPATH/pkg/mod/
    policy: pull

variables:
  # default Go version
  GO_VERSION: "1.18"
  BUILDTAGS: "include_gcs,include_oss,continuous_profiler_stackdriver"
  CGO_ENABLED: "1"
  GOPATH: $CI_PROJECT_DIR/.GOPATH
  GOTESTSUM_VERSION: v1.8.1

stages:
  - validate
  - test
  - integration
  - release
