repositoryUrl: 'git@gitlab.com:gitlab-org/container-registry.git'
tagFormat: 'v${version}-gitlab'
branches:
  - master
plugins:
  - - "@semantic-release/commit-analyzer"
    - preset: conventionalcommits
      releaseRules:
        - type: build
          release: patch
  - - "@semantic-release/release-notes-generator"
    - preset: conventionalcommits
      presetConfig:
        types:
          - type: feat
            section: "✨ Features ✨"
            hidden: false
          - type: fix
            section: "🐛 Bug Fixes 🐛"
            hidden: false
          - type: perf
            section: "⚡️ Performance Improvements ⚡️"
            hidden: false
          - type: revert
            section: "⏮️️ Reverts ⏮️️"
            hidden: false
          - type: build
            section: "⚙️ Build ⚙️"
            hidden: false
  - '@semantic-release/changelog'
  - - '@semantic-release/git'
    - assets:
        - CHANGELOG.md
      message: |-
        chore(release): ${nextRelease.version}

        ${nextRelease.notes}
