---
- name: Bump fs-notify limits
  ansible.builtin.copy:
    src: 50-fsnotify.conf
    dest: /etc/sysctl.d/50-fsnotify.conf
    owner: root
    group: root
    mode: 0644

- name: Install additional packages
  ansible.builtin.apt:
    state: present
    name:
      - sysstat
      - tree
      - nginx
  register: __pkgmgr_result
  until: __pkgmgr_result is succeeded
  retries: 3
  delay: 3

- name: Disable root login via SSH
  ansible.builtin.copy:
    dest: /etc/ssh/sshd_config.d/99-disable-root.conf
    content: |
      # Disable password auth
      PasswordAuthentication no

      # Disable root login
      PermitRootLogin no
    owner: root
    group: root
    mode: "0600"
  notify: Restart sshd

- name: Validate sshd configuration
  ansible.builtin.command: sshd -t
  changed_when: false
