environments:
  cng:
    id: '4359271'
    ref: 'master'
  charts:
    id: '3828396'
    ref: 'master'
  omnibus:
    id: '20699'
    ref: 'master'
  k8s:
    stages:
      - name: 'gprd'  
        id: '12547113'
        ref: 'master'
        mr_title: 'Bump Container Registry (gprd)'
        branch_name: 'bump-registry-version-gprd'
        commit_message: 'Bump Container Registry (gprd)'
        paths:
        - filename: bases/gprd.yaml
      - name: 'gstg/pre'
        ref: 'master'
        id: '12547113'
        mr_title: 'Bump Container Registry (gstg/pre)'
        branch_name: 'bump-registry-version-gstgpre'
        commit_message: 'Bump Container Registry (gstg/pre)'
        paths: 
          - filename: bases/pre.yaml
          - filename: bases/gstg.yaml      
  gdk:
    ref: 'main'
    id: '74823'
    mr_title: 'Bump Container Registry'
    commit_message: 'Bump Container Registry'
    branch_name: 'bump-registry-version-gdk'
    paths: 
      - filename: support/docker-registry
      - filename: lib/gdk/config.rb
      - filename: spec/lib/gdk/config_spec.rb
      - filename: gdk.example.yml
issue:
  - title: 'Release Plan'
    template: .gitlab/issue_templates/Release Plan.md
    id: '13831684'
    ref: 'master'
