---
ansible_ssh_args: --tunnel-through-iap --zone={{ zone }} --no-user-output-enabled --quiet
ansible_scp_extra_args: --tunnel-through-iap --zone={{ zone }} --quiet
ansible_python_interpreter: /usr/bin/python3

route_address: 10.15.16.0/22

docker_network: "{{ route_address | ansible.utils.ipsubnet(24, 0) }}"
docker_iprange: "{{ docker_network | ansible.utils.ipsubnet(25, 0) }}"

svc_net: "{{ route_address | ansible.utils.ipsubnet(24, 1) }}"
svc_ip: "{{ svc_net | ansible.utils.ipaddr('1') | ansible.utils.ipaddr('address') }}"

vip_net: "{{ route_address | ansible.utils.ipsubnet(24, 2) }}"
vip_start_ip: "{{ vip_net | ansible.utils.ipaddr('1') | ansible.utils.ipaddr('address') }}"
vip_end_ip: "{{ vip_net | ansible.utils.ipaddr('32') | ansible.utils.ipaddr('address') }}"

wireguard_net: "{{ route_address | ansible.utils.ipsubnet(24, 3) }}"

docker_bridge_name: br-wg

postgresql_auth_method: scram-sha-256

postgresql_hba_entries:
  - { type: local, database: all, user: postgres, auth_method: peer }
  - {
      type: host,
      database: gitlab_db,
      user: gitlab_user,
      address: "{{ wireguard_net}}",
      auth_method: "{{ postgresql_auth_method }}",
    }
  - {
      type: host,
      database: gitlab_db,
      user: gitlab_user,
      address: "{{ docker_iprange}}",
      auth_method: "{{ postgresql_auth_method }}",
    }
  - {
      type: host,
      database: gitlab_db,
      user: gitlab_user,
      address: "{{ svc_net }}",
      auth_method: "{{ postgresql_auth_method }}",
    }
  - {
      type: host,
      database: registry_db,
      user: registry_user,
      address: "{{ wireguard_net}}",
      auth_method: "{{ postgresql_auth_method }}",
    }
  - {
      type: host,
      database: registry_db,
      user: registry_user,
      address: "{{ docker_iprange}}",
      auth_method: "{{ postgresql_auth_method }}",
    }
  - {
      type: host,
      database: registry_db,
      user: registry_user,
      address: "{{ svc_net }}",
      auth_method: "{{ postgresql_auth_method }}",
    }
  - {
      type: host,
      database: ci_db,
      user: ci_user,
      address: "{{ wireguard_net}}",
      auth_method: "{{ postgresql_auth_method }}",
    }
  - {
      type: host,
      database: ci_db,
      user: ci_user,
      address: "{{ docker_iprange}}",
      auth_method: "{{ postgresql_auth_method }}",
    }
  - {
      type: host,
      database: ci_db,
      user: ci_user,
      address: "{{ svc_net }}",
      auth_method: "{{ postgresql_auth_method }}",
    }

postgresql_databases:
  - name: gitlab_db
    owner: gitlab_user
    state: present
  - name: registry_db
    owner: registry_user
    state: present
  - name: ci_db
    owner: ci_user
    state: present

# NOTE(prozlach): passwords are randomized by booter during the setup
postgresql_users:
  - name: gitlab_user
    password: chleboslaw
    db: gitlab_db
    state: present
  - name: registry_user
    password: bozyDar
    db: registry_db
    state: present
  - name: ci_user
    password: waldemar
    db: ci_db
    state: present

postgresql_global_config_options:
  - option: listen_addresses
    value: "{{ svc_ip }}"
  - option: unix_socket_directories
    value: '{{ postgresql_unix_socket_directories | join(",") }}'
  - option: log_directory
    value: "log"

postgresql_privs: []
