---
ansible_ssh_args: --tunnel-through-iap --zone={{ zone }} --no-user-output-enabled --quiet
ansible_scp_extra_args: --tunnel-through-iap --zone={{ zone }} --quiet
ansible_python_interpreter: /usr/bin/python3

route_address: 10.15.16.0/22

docker_network: "{{ route_address | ansible.utils.ipsubnet(24, 0) }}"
docker_iprange: "{{ docker_network | ansible.utils.ipsubnet(25, 0) }}"

svc_net: "{{ route_address | ansible.utils.ipsubnet(24, 1) }}"
svc_ip: "{{ svc_net | ansible.utils.ipaddr('1') | ansible.utils.ipaddr('address') }}"

vip_net: "{{ route_address | ansible.utils.ipsubnet(24, 2) }}"
vip_start_ip: "{{ vip_net | ansible.utils.ipaddr('1') | ansible.utils.ipaddr('address') }}"
vip_end_ip: "{{ vip_net | ansible.utils.ipaddr('32') | ansible.utils.ipaddr('address') }}"

wireguard_net: "{{ route_address | ansible.utils.ipsubnet(24, 3) }}"
wireguard_ui_ip: "{{ docker_network | ansible.utils.ipaddr('2') | ansible.utils.ipaddr('address') }}"

docker_bridge_name: br-wg

postgresql_auth_method: scram-sha-256

postgresql_hba_entries:
  - { type: local, database: all, user: postgres, auth_method: peer }
  - {
      type: host,
      database: gitlab_db,
      user: gitlab_user,
      address: "{{ svc_net}}",
      auth_method: "{{ postgresql_auth_method }}",
    }
  - {
      type: host,
      database: gitlab_db,
      user: gitlab_user,
      address: "{{ vip_net}}",
      auth_method: "{{ postgresql_auth_method }}",
    }
  - {
      type: host,
      database: registry_db,
      user: registry_user,
      address: "{{ svc_net}}",
      auth_method: "{{ postgresql_auth_method }}",
    }
  - {
      type: host,
      database: registry_db,
      user: registry_user,
      address: "{{ vip_net}}",
      auth_method: "{{ postgresql_auth_method }}",
    }

postgresql_databases:
  - name: gitlab_db
    owner: gitlab_user
    state: present
  - name: registry_db
    owner: registry_user
    state: present

# NOTE(prozlach): passwords are randomized by booter during the setup
postgresql_users:
  - name: gitlab_user
    password: chleboslaw
    db: gitlab_db
    state: present
  - name: registry_user
    password: bozyDar
    db: registry_db
    state: present

# TODO(prozlach):
postgresql_privs: []
# - db: exampledb # database (required)
#   roles: jdoe  # role(s) the privs apply to (required)
#   privs: # comma separated list of privileges - defaults to not set
#   type: # type of database object to set privileges on - defaults to not set
#   objs: # list of database objects to set privileges on - defaults to not set
#   schema: # defaults to not set
#   session_role: # defaults to not set
#   fail_on_role: # defaults to true
#   grant_option: # defaults to not set
#   target_roles: # defaults to not set
#   login_host: # defaults to 'localhost'
#   login_password: # defaults to not set
#   login_user: # defaults to '{{ postgresql_user }}'
#   login_unix_socket: # defaults to 1st of postgresql_unix_socket_directories
#   port: # defaults to not set
#   state: # defaults to 'present'
