services:
  redis-7000:
    image: bitnamilegacy/redis-cluster:8.0.2
    container_name: redis-7000
    network_mode: host
    environment:
      ALLOW_EMPTY_PASSWORD: yes
      REDIS_PORT_NUMBER: 7000
      REDIS_CLUSTER_ANNOUNCE_PORT: 7000
      REDIS_CLUSTER_ANNOUNCE_BUS_PORT: 17000
      REDIS_CLUSTER_DYNAMIC_IPS: no
      REDIS_CLUSTER_ANNOUNCE_IP: 127.0.0.1
      REDIS_NODES: localhost:7000 localhost:7001 localhost:7002
      REDIS_CLUSTER_REPLICAS: 0
      REDIS_CLUSTER_CREATOR: yes

  redis-7001:
    image: bitnamilegacy/redis-cluster:8.0.2
    container_name: redis-7001
    network_mode: host
    environment:
      ALLOW_EMPTY_PASSWORD: yes
      REDIS_PORT_NUMBER: 7001
      REDIS_CLUSTER_ANNOUNCE_PORT: 7001
      REDIS_CLUSTER_ANNOUNCE_BUS_PORT: 17001
      REDIS_CLUSTER_DYNAMIC_IPS: no
      REDIS_CLUSTER_ANNOUNCE_IP: 127.0.0.1
      REDIS_NODES: localhost:7000 localhost:7001 localhost:7002
      REDIS_CLUSTER_REPLICAS: 0

  redis-7002:
    image: bitnamilegacy/redis-cluster:8.0.2
    container_name: redis-7002
    network_mode: host
    environment:
      ALLOW_EMPTY_PASSWORD: yes
      REDIS_PORT_NUMBER: 7002
      REDIS_CLUSTER_ANNOUNCE_PORT: 7002
      REDIS_CLUSTER_ANNOUNCE_BUS_PORT: 17002
      REDIS_CLUSTER_DYNAMIC_IPS: no
      REDIS_CLUSTER_ANNOUNCE_IP: 127.0.0.1
      REDIS_NODES: localhost:7000 localhost:7001 localhost:7002
      REDIS_CLUSTER_REPLICAS: 0
