version: 0.1
log:
  level: info
  formatter: text
  accesslog:
    formatter: text
storage:
  delete:
    enabled: true
  filesystem:
    # Please update this with a non-temporary path where your registry data should be saved
    rootdirectory: /tmp/registry
http:
  addr: :5000
  debug:
    addr: :5001
    prometheus:
      enabled: true
      path: /metrics
