# This config file is a more advanced configuration using filesystem metadata
# and blob storage in migration mode. In migration mode repositories existing on
# the filesystem metadata will continue to be served entirely from the
# filesystem, while newly-created repositories will use the database for
# metadata and the filesystem, under a separate prefix, for blob storage.
version: 0.1
log:
  accesslog:
    disabled: false
    formatter: text
  level: info
  formatter: text
  fields:
    service: registry
storage:
  delete:
    enabled: true
  filesystem:
    # Temp dir, rename if you need persistence.
    # registry/storage/paths.go describes the structure of the data
    # written to this directory
    rootdirectory: "/tmp/registry"
database:
  enabled:  true
  host:     "localhost"
  port:     5432
  user:     "postgres"
  password: "secret"
  dbname:   "registry_test"
  sslmode:  "disable"
migration:
  enabled: true
  # By default, new repositories will continue to have their metadata written
  # to the filesystem as a backup. To write new repository metadata only to the
  # database, enable this setting.
  disablemirrorfs: false
  # Temp dir, rename if you need persistence.
  # This directory is used by new repositories to contain their blob data and
  # (optionally) a copy of their metadata.
  rootdirectory: "/tmp/registry/gitlab"
  # In a typical production environment during migration, rails would provide
  # the migration eligibility of a repository via the auth service. Enable this
  # setting in order to test migration mode without an auth service — all new
  # repositories will be considered eligible for migration.
  autheligibilitydisabled: true
http:
  # Registry API will be accessible at localhost:5000
  addr: :5000
  debug:
    addr: :5001
      # Metrics will be accessible at localhost:5001/metrics/
    prometheus:
      enabled: true
      path: /metrics
      # Profiling information will be accessible at localhost:5001/debug/pprof/
    pprof:
      enabled: true
