# This config file, along with proxied.yml, allows to start two registry instances that can
# communicate with each other, for more information see docs-gitlab/migration-proxy.md
version: 0.1
log:
  level: info
  formatter: text
  accesslog:
    formatter: text
storage:
  delete:
    enabled: true
  filesystem:
    # Please update this with a non-temporary path where your registry data should be saved
    rootdirectory: /tmp/registry
http:
  addr: :5000
  secret: registrysecret
  debug:
    addr: :5003
    prometheus:
      enabled: true
      path: /metrics
migration:
  proxy:
    enabled: true
    url: http://localhost:5002
