# This config file, along with proxy.yml, allows to start two registry instances that can
# communicate with each other, for more information see docs-gitlab/migration-proxy.md
version: 0.1
log:
  level: info
  formatter: text
  accesslog:
    formatter: text
storage:
  delete:
    enabled: true
  filesystem:
    # Please update this with a non-temporary path where your registry data should be saved
    # This should be different from the path set in proxy.yml
    rootdirectory: /tmp/registry2
http:
  host: localhost:5000
  addr: :5002
  secret: registrysecret
  debug:
    addr: :5001
    prometheus:
      enabled: true
      path: /metrics
