---
- name: Install deps
  ansible.builtin.apt:
    name:
      - golang-rice
    state: present
  register: __pkgmgr_result
  until: __pkgmgr_result is succeeded
  retries: 3
  delay: 3

- name: Checkout wireguard-ui
  ansible.builtin.git:
    repo: https://github.com/ngoduykhanh/wireguard-ui.git
    dest: /home/dev/wireguard-ui/
    accept_hostkey: true
    version: master
  # ssh auth sock issues
  become: true
  become_flags: -SHE
  become_user: dev

# We need to compile wireguard-ui from source as the latest release does not
# have all the features we need
- name: Compile wireguard-ui repo
  ansible.builtin.shell:
  args:
    cmd: |
      set -eou pipefail
      eval "$(mise activate bash)"

      go mod download
      sed -i 's/\$YARN install --pure-lockfile --production/$YARN install/' ./prepare_assets.sh
      ./prepare_assets.sh
      rice embed-go
      go build -o wireguard-ui
    chdir: /home/dev/wireguard-ui/
    executable: /bin/bash
    creates: /home/dev/wireguard-ui/wireguard-ui
  become: true
  become_user: dev
  # Node install through ASDF is pretty flakey
  register: wg_compile_result
  until: "wg_compile_result is not failed"
  retries: 3
  delay: 5

- name: Copy wireguard binary
  ansible.builtin.copy:
    src: /home/dev/wireguard-ui/wireguard-ui
    dest: /usr/bin/wireguard-ui
    mode: 0755
    owner: root
    group: root
    force: yes
    remote_src: true

- name: Create wireguard-ui conf directory
  ansible.builtin.file:
    path: /etc/wireguard-ui/
    state: directory
    mode: 0700
    owner: root
    group: root

- name: Create wireguard-ui configuration file
  ansible.builtin.template:
    src: wireguard-ui.conf.j2
    dest: /etc/wireguard-ui/wireguard-ui.conf
    owner: root
    group: root
    mode: 0600

- name: Copy systemd service
  ansible.builtin.copy:
    src: files/wireguard-ui.service
    dest: /etc/systemd/system/wireguard-ui.service
    mode: 0644
    owner: root
    group: root

- name: Create auto restart Wireguard daemon services (monitors for conf changes from wireguard-ui)
  ansible.builtin.copy:
    src: files/{{ item }}
    dest: /etc/systemd/system/
    mode: 0644
    owner: root
    group: root
  with_items:
    - wgui.path
    - wgui.service

# Will be enabled by booter once passwords are generated
- name: disable wireguard-ui service
  ansible.builtin.service:
    name: wireguard-ui
    state: stopped
    enabled: false

# Will be enabled by booter once passwords are generated
- name: disable auto restart services
  ansible.builtin.service:
    name: "{{ item }}"
    state: stopped
    enabled: false
  with_items:
    - wgui.path
    - wireguard-ui

# Will be enabled by booter once passwords are generated
- name: disable wgui.service
  ansible.builtin.service:
    name: wgui.service
    enabled: false

- name: Remove wireguard-ui data to make sure that machie starts with clean slate
  ansible.builtin.file:
    path: /db/
    state: absent
