// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/docker/distribution/registry/datastore (interfaces: GCBlobTaskStore)
//
// Generated by this command:
//
//	mockgen -package mocks -destination mocks/gcblobtask.go . GCBlobTaskStore
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	models "github.com/docker/distribution/registry/datastore/models"
	gomock "go.uber.org/mock/gomock"
)

// MockGCBlobTaskStore is a mock of GCBlobTaskStore interface.
type MockGCBlobTaskStore struct {
	ctrl     *gomock.Controller
	recorder *MockGCBlobTaskStoreMockRecorder
	isgomock struct{}
}

// MockGCBlobTaskStoreMockRecorder is the mock recorder for MockGCBlobTaskStore.
type MockGCBlobTaskStoreMockRecorder struct {
	mock *MockGCBlobTaskStore
}

// NewMockGCBlobTaskStore creates a new mock instance.
func NewMockGCBlobTaskStore(ctrl *gomock.Controller) *MockGCBlobTaskStore {
	mock := &MockGCBlobTaskStore{ctrl: ctrl}
	mock.recorder = &MockGCBlobTaskStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGCBlobTaskStore) EXPECT() *MockGCBlobTaskStoreMockRecorder {
	return m.recorder
}

// Count mocks base method.
func (m *MockGCBlobTaskStore) Count(ctx context.Context) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count", ctx)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Count indicates an expected call of Count.
func (mr *MockGCBlobTaskStoreMockRecorder) Count(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockGCBlobTaskStore)(nil).Count), ctx)
}

// Delete mocks base method.
func (m *MockGCBlobTaskStore) Delete(ctx context.Context, b *models.GCBlobTask) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, b)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockGCBlobTaskStoreMockRecorder) Delete(ctx, b any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockGCBlobTaskStore)(nil).Delete), ctx, b)
}

// FindAll mocks base method.
func (m *MockGCBlobTaskStore) FindAll(ctx context.Context) ([]*models.GCBlobTask, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", ctx)
	ret0, _ := ret[0].([]*models.GCBlobTask)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockGCBlobTaskStoreMockRecorder) FindAll(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockGCBlobTaskStore)(nil).FindAll), ctx)
}

// IsDangling mocks base method.
func (m *MockGCBlobTaskStore) IsDangling(ctx context.Context, b *models.GCBlobTask) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsDangling", ctx, b)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsDangling indicates an expected call of IsDangling.
func (mr *MockGCBlobTaskStoreMockRecorder) IsDangling(ctx, b any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsDangling", reflect.TypeOf((*MockGCBlobTaskStore)(nil).IsDangling), ctx, b)
}

// Next mocks base method.
func (m *MockGCBlobTaskStore) Next(ctx context.Context) (*models.GCBlobTask, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Next", ctx)
	ret0, _ := ret[0].(*models.GCBlobTask)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Next indicates an expected call of Next.
func (mr *MockGCBlobTaskStoreMockRecorder) Next(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Next", reflect.TypeOf((*MockGCBlobTaskStore)(nil).Next), ctx)
}

// Postpone mocks base method.
func (m *MockGCBlobTaskStore) Postpone(ctx context.Context, b *models.GCBlobTask, d time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Postpone", ctx, b, d)
	ret0, _ := ret[0].(error)
	return ret0
}

// Postpone indicates an expected call of Postpone.
func (mr *MockGCBlobTaskStoreMockRecorder) Postpone(ctx, b, d any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Postpone", reflect.TypeOf((*MockGCBlobTaskStore)(nil).Postpone), ctx, b, d)
}
