// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/docker/distribution/registry/datastore (interfaces: RepositoryCache)
//
// Generated by this command:
//
//	mockgen -package mocks -destination mocks/repository.go . RepositoryCache
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/docker/distribution/registry/datastore/models"
	gomock "go.uber.org/mock/gomock"
)

// MockRepositoryCache is a mock of RepositoryCache interface.
type MockRepositoryCache struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryCacheMockRecorder
}

// MockRepositoryCacheMockRecorder is the mock recorder for MockRepositoryCache.
type MockRepositoryCacheMockRecorder struct {
	mock *MockRepositoryCache
}

// NewMockRepositoryCache creates a new mock instance.
func NewMockRepositoryCache(ctrl *gomock.Controller) *MockRepositoryCache {
	mock := &MockRepositoryCache{ctrl: ctrl}
	mock.recorder = &MockRepositoryCacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepositoryCache) EXPECT() *MockRepositoryCacheMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockRepositoryCache) Get(arg0 context.Context, arg1 string) *models.Repository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1)
	ret0, _ := ret[0].(*models.Repository)
	return ret0
}

// Get indicates an expected call of Get.
func (mr *MockRepositoryCacheMockRecorder) Get(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockRepositoryCache)(nil).Get), arg0, arg1)
}

// GetLSN mocks base method.
func (m *MockRepositoryCache) GetLSN(arg0 context.Context, arg1 *models.Repository) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLSN", arg0, arg1)
	ret0, _ := ret[0].(string)
	return ret0
}

// GetLSN indicates an expected call of GetLSN.
func (mr *MockRepositoryCacheMockRecorder) GetLSN(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLSN", reflect.TypeOf((*MockRepositoryCache)(nil).GetLSN), arg0, arg1)
}

// GetSizeWithDescendants mocks base method.
func (m *MockRepositoryCache) GetSizeWithDescendants(arg0 context.Context, arg1 *models.Repository) (bool, int64) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSizeWithDescendants", arg0, arg1)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(int64)
	return ret0, ret1
}

// GetSizeWithDescendants indicates an expected call of GetSizeWithDescendants.
func (mr *MockRepositoryCacheMockRecorder) GetSizeWithDescendants(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSizeWithDescendants", reflect.TypeOf((*MockRepositoryCache)(nil).GetSizeWithDescendants), arg0, arg1)
}

// HasSizeWithDescendantsTimedOut mocks base method.
func (m *MockRepositoryCache) HasSizeWithDescendantsTimedOut(arg0 context.Context, arg1 *models.Repository) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasSizeWithDescendantsTimedOut", arg0, arg1)
	ret0, _ := ret[0].(bool)
	return ret0
}

// HasSizeWithDescendantsTimedOut indicates an expected call of HasSizeWithDescendantsTimedOut.
func (mr *MockRepositoryCacheMockRecorder) HasSizeWithDescendantsTimedOut(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasSizeWithDescendantsTimedOut", reflect.TypeOf((*MockRepositoryCache)(nil).HasSizeWithDescendantsTimedOut), arg0, arg1)
}

// InvalidateSize mocks base method.
func (m *MockRepositoryCache) InvalidateSize(arg0 context.Context, arg1 *models.Repository) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "InvalidateSize", arg0, arg1)
}

// InvalidateSize indicates an expected call of InvalidateSize.
func (mr *MockRepositoryCacheMockRecorder) InvalidateSize(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InvalidateSize", reflect.TypeOf((*MockRepositoryCache)(nil).InvalidateSize), arg0, arg1)
}

// Set mocks base method.
func (m *MockRepositoryCache) Set(arg0 context.Context, arg1 *models.Repository) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Set", arg0, arg1)
}

// Set indicates an expected call of Set.
func (mr *MockRepositoryCacheMockRecorder) Set(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockRepositoryCache)(nil).Set), arg0, arg1)
}

// SetLSN mocks base method.
func (m *MockRepositoryCache) SetLSN(arg0 context.Context, arg1 *models.Repository, arg2 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetLSN", arg0, arg1, arg2)
}

// SetLSN indicates an expected call of SetLSN.
func (mr *MockRepositoryCacheMockRecorder) SetLSN(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetLSN", reflect.TypeOf((*MockRepositoryCache)(nil).SetLSN), arg0, arg1, arg2)
}

// SetSizeWithDescendants mocks base method.
func (m *MockRepositoryCache) SetSizeWithDescendants(arg0 context.Context, arg1 *models.Repository, arg2 int64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetSizeWithDescendants", arg0, arg1, arg2)
}

// SetSizeWithDescendants indicates an expected call of SetSizeWithDescendants.
func (mr *MockRepositoryCacheMockRecorder) SetSizeWithDescendants(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetSizeWithDescendants", reflect.TypeOf((*MockRepositoryCache)(nil).SetSizeWithDescendants), arg0, arg1, arg2)
}

// SizeWithDescendantsTimedOut mocks base method.
func (m *MockRepositoryCache) SizeWithDescendantsTimedOut(arg0 context.Context, arg1 *models.Repository) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SizeWithDescendantsTimedOut", arg0, arg1)
}

// SizeWithDescendantsTimedOut indicates an expected call of SizeWithDescendantsTimedOut.
func (mr *MockRepositoryCacheMockRecorder) SizeWithDescendantsTimedOut(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SizeWithDescendantsTimedOut", reflect.TypeOf((*MockRepositoryCache)(nil).SizeWithDescendantsTimedOut), arg0, arg1)
}
