// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/docker/distribution/registry/auth (interfaces: AccessController)
//
// Generated by this command:
//
//	mockgen -package mocks -destination mocks/access_controller.go . AccessController
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	auth "github.com/docker/distribution/registry/auth"
	gomock "go.uber.org/mock/gomock"
)

// MockAccessController is a mock of AccessController interface.
type MockAccessController struct {
	ctrl     *gomock.Controller
	recorder *MockAccessControllerMockRecorder
	isgomock struct{}
}

// MockAccessControllerMockRecorder is the mock recorder for MockAccessController.
type MockAccessControllerMockRecorder struct {
	mock *MockAccessController
}

// NewMockAccessController creates a new mock instance.
func NewMockAccessController(ctrl *gomock.Controller) *MockAccessController {
	mock := &MockAccessController{ctrl: ctrl}
	mock.recorder = &MockAccessControllerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccessController) EXPECT() *MockAccessControllerMockRecorder {
	return m.recorder
}

// Authorized mocks base method.
func (m *MockAccessController) Authorized(ctx context.Context, access ...auth.Access) (context.Context, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range access {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Authorized", varargs...)
	ret0, _ := ret[0].(context.Context)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Authorized indicates an expected call of Authorized.
func (mr *MockAccessControllerMockRecorder) Authorized(ctx any, access ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, access...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Authorized", reflect.TypeOf((*MockAccessController)(nil).Authorized), varargs...)
}
