// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/docker/distribution/registry/auth (interfaces: Challenge)
//
// Generated by this command:
//
//	mockgen -package mocks -destination mocks/auth_challenge.go . Challenge
//

// Package mocks is a generated GoMock package.
package mocks

import (
	http "net/http"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockChallenge is a mock of Challenge interface.
type MockChallenge struct {
	ctrl     *gomock.Controller
	recorder *MockChallengeMockRecorder
	isgomock struct{}
}

// MockChallengeMockRecorder is the mock recorder for MockChallenge.
type MockChallengeMockRecorder struct {
	mock *MockChallenge
}

// NewMockChallenge creates a new mock instance.
func NewMockChallenge(ctrl *gomock.Controller) *MockChallenge {
	mock := &MockChallenge{ctrl: ctrl}
	mock.recorder = &MockChallengeMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChallenge) EXPECT() *MockChallengeMockRecorder {
	return m.recorder
}

// Error mocks base method.
func (m *MockChallenge) Error() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Error")
	ret0, _ := ret[0].(string)
	return ret0
}

// Error indicates an expected call of Error.
func (mr *MockChallengeMockRecorder) Error() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Error", reflect.TypeOf((*MockChallenge)(nil).Error))
}

// SetHeaders mocks base method.
func (m *MockChallenge) SetHeaders(r *http.Request, w http.ResponseWriter) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetHeaders", r, w)
}

// SetHeaders indicates an expected call of SetHeaders.
func (mr *MockChallengeMockRecorder) SetHeaders(r, w any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetHeaders", reflect.TypeOf((*MockChallenge)(nil).SetHeaders), r, w)
}
