// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/docker/distribution/registry/storage/driver (interfaces: StorageDeleter)
//
// Generated by this command:
//
//	mockgen -package mocks -destination mocks/storagedriver.go . StorageDeleter
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockStorageDeleter is a mock of StorageDeleter interface.
type MockStorageDeleter struct {
	ctrl     *gomock.Controller
	recorder *MockStorageDeleterMockRecorder
	isgomock struct{}
}

// MockStorageDeleterMockRecorder is the mock recorder for MockStorageDeleter.
type MockStorageDeleterMockRecorder struct {
	mock *MockStorageDeleter
}

// NewMockStorageDeleter creates a new mock instance.
func NewMockStorageDeleter(ctrl *gomock.Controller) *MockStorageDeleter {
	mock := &MockStorageDeleter{ctrl: ctrl}
	mock.recorder = &MockStorageDeleterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorageDeleter) EXPECT() *MockStorageDeleterMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockStorageDeleter) Delete(ctx context.Context, path string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, path)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockStorageDeleterMockRecorder) Delete(ctx, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockStorageDeleter)(nil).Delete), ctx, path)
}

// DeleteFiles mocks base method.
func (m *MockStorageDeleter) DeleteFiles(ctx context.Context, paths []string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteFiles", ctx, paths)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteFiles indicates an expected call of DeleteFiles.
func (mr *MockStorageDeleterMockRecorder) DeleteFiles(ctx, paths any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFiles", reflect.TypeOf((*MockStorageDeleter)(nil).DeleteFiles), ctx, paths)
}
